"""Narration Provider abstraction and deterministic placeholder audio synthesizer."""

from __future__ import annotations

import asyncio
import uuid
from pathlib import Path
from typing import Any

from omega.application.media_storage import LocalMediaStorageProvider, compute_sha256
from omega.domain.production import (
    AssetProviderType,
    AssetType,
    LicenseStatus,
)


class PlaceholderNarrationProvider:
    """Generates deterministic narration audio (silent AAC or tone) of exact planned duration."""

    def __init__(self, storage: LocalMediaStorageProvider) -> None:
        self.storage = storage

    async def synthesize_segment_audio(
        self,
        channel_id: uuid.UUID,
        request_id: uuid.UUID,
        segment: dict[str, Any],
    ) -> dict[str, Any]:
        """Synthesize deterministic audio for a narration segment and persist as a ProductionAsset."""
        narration_dir = self.storage.get_narration_dir(channel_id, request_id)
        asset_id = uuid.uuid4()
        file_name = f"audio_{asset_id.hex[:10]}.aac"
        target_path = narration_dir / file_name

        duration_ms = max(int(segment.get("duration_ms", 3000)), 500)
        duration_sec = duration_ms / 1000.0

        # Generate silent AAC audio with exact duration via FFmpeg
        cmd = [
            "ffmpeg",
            "-y",
            "-f",
            "lavfi",
            "-i",
            f"anullsrc=r=44100:cl=stereo:d={duration_sec:.3f}",
            "-c:a",
            "aac",
            "-b:a",
            "128k",
            str(target_path),
        ]

        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
        await proc.communicate()

        if not target_path.exists() or target_path.stat().st_size == 0:
            # Fallback minimal 0.5s silent AAC header bytes for testing when ffmpeg subprocess is unavailable
            _write_fallback_aac(target_path)

        content_hash = compute_sha256(target_path)
        rel_uri = self.storage.to_relative_uri(channel_id, request_id, target_path)

        return {
            "id": asset_id,
            "channel_id": channel_id,
            "production_request_id": request_id,
            "asset_requirement_id": None,
            "asset_type": AssetType.AUDIO.value,
            "provider_type": AssetProviderType.PLACEHOLDER.value,
            "storage_uri": rel_uri,
            "content_hash": content_hash,
            "mime_type": "audio/aac",
            "width": None,
            "height": None,
            "duration_ms": duration_ms,
            "license_status": LicenseStatus.GENERATED.value,
            "source_ref": f"Synthesized silence ({duration_ms}ms)",
            "attribution": "Generated by OMEGA Narration Engine",
        }


def _write_fallback_aac(target_path: Path) -> None:
    """Write fallback AAC bytes."""
    # Minimal ADTS AAC silent frame bytes
    aac_bytes = b"\xff\xf1\x50\x80\x01\x1f\xfc" * 20
    target_path.write_bytes(aac_bytes)
