"""Narration Provider abstraction and deterministic local speech synthesizer."""

from __future__ import annotations

import asyncio
import base64
import hashlib
import math
import os
import re
import struct
import tempfile
import uuid
import wave
from pathlib import Path
from typing import Any, Protocol

from omega.application.local_tts.chunker import chunk_narration_segment
from omega.application.local_tts.engine import LocalTTSEngine, LocalTTSError
from omega.application.local_tts.kokoro_engine import KokoroLocalTTSEngine
from omega.application.media_storage import LocalMediaStorageProvider, compute_sha256
from omega.domain.production import (
    AssetProviderType,
    AssetType,
    LicenseStatus,
    NarrationQuality,
)


class NarrationProviderError(Exception):
    """Base error for narration provider failures."""


class NarrationProvider(Protocol):
    """Protocol for speech narration synthesis providers."""

    async def synthesize_segment_audio(
        self,
        channel_id: uuid.UUID,
        request_id: uuid.UUID,
        segment: dict[str, Any],
        voice_profile: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Synthesize audible speech audio for a narration segment and persist as a ProductionAsset."""
        ...


def clean_text_for_flite(text: str) -> str:
    """Clean and escape narration text for the FFmpeg flite filter (backward compatibility)."""
    clean = text.replace("\r", " ").replace("\n", " ").replace("\t", " ")
    clean = re.sub(r"[^a-zA-Z0-9\s.,?!'\-]", " ", clean)
    clean = " ".join(clean.split()).strip()
    escaped = clean.replace("\\", "\\\\").replace("'", "\\'")
    return escaped or "Technical Overview"


class NeuralTTSNarrationProvider:
    """Production-grade neural TTS provider using OpenAI Audio Speech API without silent local fallback."""

    def __init__(
        self,
        storage: LocalMediaStorageProvider,
        api_key: str | None = None,
        default_voice: str = "onyx",
    ) -> None:
        self.storage = storage
        self.api_key = api_key or os.getenv("OPENAI_API_KEY")
        self.default_voice = os.getenv("TTS_VOICE", default_voice)

    async def synthesize_segment_audio(
        self,
        channel_id: uuid.UUID,
        request_id: uuid.UUID,
        segment: dict[str, Any],
        voice_profile: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Synthesize high-fidelity neural narration audio via OpenAI TTS. Fails explicitly on error."""
        if not self.api_key:
            raise NarrationProviderError("OPENAI_API_KEY missing for neural TTS provider")

        import httpx

        narration_dir = self.storage.get_narration_dir(channel_id, request_id)
        asset_id = uuid.uuid4()
        file_name = f"neural_audio_{asset_id.hex[:10]}.aac"
        target_path = narration_dir / file_name

        text = str(segment.get("text", "")).strip()
        duration_ms = max(int(segment.get("duration_ms", 3000)), 500)
        voice = (voice_profile or {}).get("voice_ref") or self.default_voice
        speed = float((voice_profile or {}).get("speaking_rate") or os.getenv("TTS_SPEED", "1.0"))

        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": os.getenv("TTS_MODEL", "tts-1-hd"),
            "input": text,
            "voice": voice,
            "response_format": "aac",
            "speed": max(0.25, min(4.0, speed)),
        }

        try:
            async with httpx.AsyncClient(timeout=30.0) as client:
                resp = await client.post("https://api.openai.com/v1/audio/speech", headers=headers, json=payload)
                if resp.status_code == 200 and len(resp.content) > 100:
                    target_path.write_bytes(resp.content)
                    content_hash = compute_sha256(target_path)
                    rel_uri = self.storage.to_relative_uri(channel_id, request_id, target_path)
                    return {
                        "id": asset_id,
                        "channel_id": channel_id,
                        "production_request_id": request_id,
                        "asset_requirement_id": None,
                        "asset_type": AssetType.AUDIO.value,
                        "provider_type": AssetProviderType.SYSTEM.value,
                        "storage_uri": rel_uri,
                        "content_hash": content_hash,
                        "mime_type": "audio/aac",
                        "width": None,
                        "height": None,
                        "duration_ms": duration_ms,
                        "license_status": LicenseStatus.GENERATED.value,
                        "source_ref": f"OpenAI Neural TTS (voice: {voice})",
                        "attribution": "Generated by OMEGA Neural Narration Engine",
                        "narration_quality": NarrationQuality.NEURAL_PRODUCTION.value,
                    }
                raise NarrationProviderError(f"OpenAI API returned error status: {resp.status_code}")
        except NarrationProviderError:
            raise
        except Exception as e:
            raise NarrationProviderError(f"OpenAI Neural TTS synthesis failed: {e}") from e


class GeminiTTSNarrationProvider:
    """Production-grade neural TTS provider using Gemini GenerateContent REST API."""

    def __init__(
        self,
        storage: LocalMediaStorageProvider,
        api_key: str | None = None,
        model: str | None = None,
        default_voice: str | None = None,
        client: Any | None = None,
    ) -> None:
        self.storage = storage
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        self.model = model or os.getenv("GEMINI_TTS_MODEL", "gemini-3.1-flash-tts-preview")
        self.default_voice = default_voice or os.getenv("GEMINI_TTS_VOICE", "Kore")
        self.client = client

    async def synthesize_segment_audio(
        self,
        channel_id: uuid.UUID,
        request_id: uuid.UUID,
        segment: dict[str, Any],
        voice_profile: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Synthesize high-fidelity neural narration audio via Gemini TTS."""
        if not self.api_key:
            raise NarrationProviderError("GEMINI_API_KEY missing for gemini TTS provider")

        import httpx

        narration_dir = self.storage.get_narration_dir(channel_id, request_id)

        text = str(segment.get("text", "")).strip()
        voice = (voice_profile or {}).get("voice_ref")
        if not voice or voice == "neutral_default":
            voice = self.default_voice
        lang = (voice_profile or {}).get("language") or "en"
        if lang.startswith("en"):
            lang = "natural American English / en-US"
        style = (voice_profile or {}).get("style") or "natural documentary narration"
        speaking_rate = (voice_profile or {}).get("speaking_rate")
        pitch = (voice_profile or {}).get("pitch")

        instruction = (
            f"Read the following narration exactly as written. "
            f"No added words. No omitted words. "
            f"Delivery style: {style}. "
            f"Language: {lang}. "
            f"Do not use exaggerated advertisement delivery. "
        )
        if speaking_rate:
            instruction += f"Speaking rate: {speaking_rate}. "
        if pitch:
            instruction += f"Pitch: {pitch}. "
        instruction += f"\n\nNarration text:\n{text}"

        fingerprint_data = f"gemini:{self.model}:{voice}:{instruction}".encode()
        fingerprint = hashlib.sha256(fingerprint_data).hexdigest()
        file_name = f"gemini_tts_{fingerprint[:16]}.wav"
        target_path = narration_dir / file_name

        if target_path.exists() and target_path.stat().st_size > 0:
            content_hash = compute_sha256(target_path)
            rel_uri = self.storage.to_relative_uri(channel_id, request_id, target_path)

            try:
                with wave.open(str(target_path), "rb") as wav_file:
                    frames = wav_file.getnframes()
                    frame_rate = wav_file.getframerate()
                    duration_ms = int(frames / frame_rate * 1000)
            except wave.Error as e:
                raise NarrationProviderError("Cached WAV file is malformed or not a valid WAV") from e

            return {
                "id": uuid.uuid4(),
                "channel_id": channel_id,
                "production_request_id": request_id,
                "asset_requirement_id": None,
                "asset_type": AssetType.AUDIO.value,
                "provider_type": AssetProviderType.SYSTEM.value,
                "storage_uri": rel_uri,
                "content_hash": content_hash,
                "mime_type": "audio/wav",
                "width": None,
                "height": None,
                "duration_ms": duration_ms,
                "license_status": LicenseStatus.GENERATED.value,
                "source_ref": f"Gemini TTS (voice: {voice})",
                "attribution": "Generated by OMEGA Gemini TTS Engine",
                "narration_quality": NarrationQuality.NEURAL_PRODUCTION.value,
            }

        headers = {
            "x-goog-api-key": self.api_key,
            "Content-Type": "application/json",
        }
        payload = {
            "contents": [{"parts": [{"text": instruction}]}],
            "generationConfig": {
                "responseModalities": ["AUDIO"],
                "speechConfig": {
                    "voiceConfig": {
                        "prebuiltVoiceConfig": {
                            "voiceName": voice
                        }
                    }
                }
            }
        }

        client = self.client or httpx.AsyncClient(timeout=30.0)
        try:
            resp = await client.post(
                f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent",
                headers=headers,
                json=payload
            )
            resp.raise_for_status()
        except httpx.HTTPStatusError as e:
            if not self.client:
                await client.aclose()
            err_msg = f"Gemini API returned status code {e.response.status_code}"
            try:
                err_data = e.response.json()
                reason = err_data.get("error", {}).get("message", "")
                if reason:
                    err_msg += f": {reason}"
            except Exception:
                pass
            raise NarrationProviderError(err_msg) from None
        except httpx.RequestError:
            if not self.client:
                await client.aclose()
            raise NarrationProviderError("Network error calling Gemini API") from None

        if not self.client:
            await client.aclose()

        try:
            resp_data = resp.json()
            data_b64 = resp_data["candidates"][0]["content"]["parts"][0]["inlineData"]["data"]
            pcm_bytes = base64.b64decode(data_b64, validate=True)
        except (KeyError, IndexError, ValueError, TypeError):
            raise NarrationProviderError("Malformed response shape or invalid base64") from None

        if not pcm_bytes or len(pcm_bytes) < 100:
            raise NarrationProviderError("Empty or trivially small PCM data")
        if len(pcm_bytes) % 2 != 0:
            raise NarrationProviderError("Odd PCM byte count")

        with wave.open(str(target_path), "wb") as wav_file:
            wav_file.setnchannels(1)
            wav_file.setsampwidth(2)
            wav_file.setframerate(24000)
            wav_file.writeframes(pcm_bytes)

        duration_ms = int(len(pcm_bytes) / (24000 * 2) * 1000)
        content_hash = compute_sha256(target_path)
        rel_uri = self.storage.to_relative_uri(channel_id, request_id, target_path)

        return {
            "id": uuid.uuid4(),
            "channel_id": channel_id,
            "production_request_id": request_id,
            "asset_requirement_id": None,
            "asset_type": AssetType.AUDIO.value,
            "provider_type": AssetProviderType.SYSTEM.value,
            "storage_uri": rel_uri,
            "content_hash": content_hash,
            "mime_type": "audio/wav",
            "width": None,
            "height": None,
            "duration_ms": duration_ms,
            "license_status": LicenseStatus.GENERATED.value,
            "source_ref": f"Gemini TTS (voice: {voice})",
            "attribution": "Generated by OMEGA Gemini TTS Engine",
            "narration_quality": NarrationQuality.NEURAL_PRODUCTION.value,
        }


class LocalTTSNarrationProvider:
    """Production local TTS narration provider delegating to a LocalTTSEngine abstraction."""

    def __init__(
        self,
        storage: LocalMediaStorageProvider,
        engine: LocalTTSEngine | None = None,
        profile: str | None = None,
    ) -> None:
        self.storage = storage
        self.profile = profile or os.getenv("LOCAL_TTS_PROFILE", "quality")
        self._engine = engine

    @property
    def engine(self) -> LocalTTSEngine:
        """Lazily initialize or return configured LocalTTSEngine."""
        if self._engine is None:
            self._engine = KokoroLocalTTSEngine(default_profile=self.profile)
        return self._engine

    async def synthesize_segment_audio(
        self,
        channel_id: uuid.UUID,
        request_id: uuid.UUID,
        segment: dict[str, Any],
        voice_profile: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Synthesize audible speech audio for a narration segment and persist as a ProductionAsset."""
        narration_dir = self.storage.get_narration_dir(channel_id, request_id)
        asset_id = uuid.uuid4()
        file_name = f"audio_{asset_id.hex[:10]}.wav"
        target_path = narration_dir / file_name

        text = str(segment.get("text", "")).strip()
        if not text:
            raise NarrationProviderError("Empty narration text for synthesis")

        # Single authoritative policy resolution
        from omega.application.local_tts.policy import (
            ResolvedNarrationPolicy,
            resolve_narration_policy,
        )

        if isinstance(voice_profile, ResolvedNarrationPolicy):
            policy = voice_profile
        else:
            policy = resolve_narration_policy(
                request_policy=voice_profile,
                actual_provider="LOCAL_TTS",
            )

        voice = policy.voice
        language = policy.language
        speed = policy.speed
        profile = policy.profile

        # Apply semantic chunking policy (splits only if segment exceeds upper token threshold)
        chunks = chunk_narration_segment(text)

        try:
            if len(chunks) <= 1:
                # Single chunk synthesis
                result = await self.engine.synthesize(
                    text=text,
                    output_path=target_path,
                    voice=voice,
                    language=language,
                    speed=speed,
                    profile=profile,
                )
            else:
                # Multi-chunk synthesis concatenated into single canonical WAV
                result = await self._synthesize_multi_chunks(
                    chunks=chunks,
                    target_path=target_path,
                    voice=voice,
                    language=language,
                    speed=speed,
                    profile=profile,
                )
        except (LocalTTSError, Exception) as e:
            # Explicit failure policy: NO fallback to sine waves or cloud APIs
            raise NarrationProviderError(f"Local TTS narration synthesis failed: {e}") from e

        content_hash = result.content_hash
        rel_uri = self.storage.to_relative_uri(channel_id, request_id, target_path)

        return {
            "id": asset_id,
            "channel_id": channel_id,
            "production_request_id": request_id,
            "asset_requirement_id": None,
            "asset_type": AssetType.AUDIO.value,
            "provider_type": AssetProviderType.SYSTEM.value,
            "storage_uri": rel_uri,
            "content_hash": content_hash,
            "mime_type": "audio/wav",
            "width": None,
            "height": None,
            "duration_ms": result.duration_ms,
            "license_status": LicenseStatus.GENERATED.value,
            "source_ref": f"Local TTS (engine: {result.engine}, voice: {result.voice})",
            "attribution": "Generated by OMEGA Kokoro Local TTS Engine",
            "narration_quality": NarrationQuality.NEURAL_PRODUCTION.value,
            # Provenance metadata
            "provider": "LOCAL_TTS",
            "engine": result.engine,
            "model": result.model,
            "profile": result.profile,
            "voice": result.voice,
            "language": result.language,
            "speed": result.speed,
            "device": result.device,
            "native_sample_rate": result.native_sample_rate,
            "canonical_sample_rate": result.canonical_sample_rate,
            "generation_duration_ms": result.generation_duration_ms,
        }

    async def _synthesize_multi_chunks(
        self,
        chunks: list[str],
        target_path: Path,
        voice: str | None,
        language: str | None,
        speed: float | None,
        profile: str | None = None,
    ) -> Any:
        """Synthesize multiple semantic chunks sequentially and concatenate to target WAV."""
        temp_paths: list[Path] = []
        total_gen_ms = 0
        last_result = None

        with tempfile.TemporaryDirectory() as tmp_dir:
            tmp_root = Path(tmp_dir)
            for idx, chunk in enumerate(chunks):
                chunk_path = tmp_root / f"chunk_{idx}.wav"
                res = await self.engine.synthesize(
                    text=chunk,
                    output_path=chunk_path,
                    voice=voice,
                    language=language,
                    speed=speed,
                    profile=profile or self.profile,
                )
                temp_paths.append(chunk_path)
                total_gen_ms += res.generation_duration_ms
                last_result = res

            # Concat using FFmpeg
            filter_inputs = "".join(f"[{i}:a]" for i in range(len(temp_paths)))
            filter_str = f"{filter_inputs}concat=n={len(temp_paths)}:v=0:a=1[out]"
            cmd = ["ffmpeg", "-y"]
            for p in temp_paths:
                cmd.extend(["-i", str(p)])
            cmd.extend([
                "-filter_complex", filter_str,
                "-map", "[out]",
                "-c:a", "pcm_s16le",
                "-ar", "44100",
                "-ac", "1",
                str(target_path),
            ])

            proc = await asyncio.create_subprocess_exec(
                *cmd,
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.PIPE,
            )
            _, stderr = await proc.communicate()
            if proc.returncode != 0 or not target_path.exists():
                err_msg = stderr.decode("utf-8", errors="replace")
                raise NarrationProviderError(f"Audio chunk concatenation failed: {err_msg}")

        # Compute duration and SHA-256 over concatenated canonical output
        with wave.open(str(target_path), "rb") as w:
            frames = w.getnframes()
            rate = w.getframerate()
            duration_ms = int(frames / rate * 1000)

        content_sha = compute_sha256(target_path)

        from omega.application.local_tts.engine import SynthesisResult
        return SynthesisResult(
            audio_path=target_path,
            duration_ms=duration_ms,
            native_sample_rate=last_result.native_sample_rate if last_result else 24000,
            canonical_sample_rate=44100,
            channels=1,
            engine=last_result.engine if last_result else "kokoro-onnx",
            model=last_result.model if last_result else "kokoro-v1.0.fp16",
            voice=last_result.voice if last_result else "af_heart",
            language=last_result.language if last_result else "en-US",
            speed=last_result.speed if last_result else 1.0,
            device=last_result.device if last_result else "cpu",
            generation_duration_ms=total_gen_ms,
            content_hash=content_sha,
            profile=self.profile,
        )


def get_narration_provider(storage: LocalMediaStorageProvider) -> NarrationProvider:
    """Factory creating configured speech narration provider. Explicit, no silent fallback."""
    provider_type = os.getenv("TTS_PROVIDER", "local").lower()
    if provider_type == "gemini":
        if not os.getenv("GEMINI_API_KEY"):
            raise NarrationProviderError("GEMINI_API_KEY missing for gemini TTS provider")
        return GeminiTTSNarrationProvider(storage)
    if provider_type in ("neural", "openai", "cloud"):
        if not os.getenv("OPENAI_API_KEY"):
            raise NarrationProviderError("OPENAI_API_KEY missing for neural/cloud TTS provider")
        return NeuralTTSNarrationProvider(storage)
    return LocalTTSNarrationProvider(storage)


def _generate_audible_fallback_wav(target_wav_path: Path, text: str, duration_sec: float) -> None:
    """Generate audible deterministic modulated waveform audio (legacy test helper)."""
    sample_rate = 22050
    num_samples = int(sample_rate * max(duration_sec, 1.0))
    base_freq = 220.0 + (abs(hash(text)) % 150)
    with wave.open(str(target_wav_path), "wb") as wav_file:
        wav_file.setnchannels(1)
        wav_file.setsampwidth(2)
        wav_file.setframerate(sample_rate)
        frames = bytearray()
        for i in range(num_samples):
            t = i / sample_rate
            cadence = 0.5 * (1.0 + math.sin(2.0 * math.pi * 4.0 * t))
            sample = int(14000.0 * cadence * math.sin(2.0 * math.pi * base_freq * t))
            frames.extend(struct.pack("<h", max(-32767, min(32767, sample))))
        wav_file.writeframes(frames)


def _write_fallback_aac(target_path: Path) -> None:
    """Write minimal non-empty ADTS AAC frame bytes (legacy test helper)."""
    aac_bytes = b"\xff\xf1\x50\x80\x01\x1f\xfc\x00\x00\x00\x00" * 40
    target_path.write_bytes(aac_bytes)


# Backward-compatibility alias
PlaceholderNarrationProvider = LocalTTSNarrationProvider
