"""Mission Planner abstraction and implementations.

Generates validated task DAGs for missions.
No real AI or domain engine execution occurs here.
"""

from __future__ import annotations

import uuid
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Any

from omega.domain.dag import validate_dag
from omega.domain.task import TaskCreate


@dataclass
class PlannedTask:
    """A task definition prepared by a planner before database persistence."""

    temp_id: uuid.UUID
    task_create: TaskCreate


@dataclass
class PlannedDependency:
    """A dependency definition between planned tasks (task_temp_id depends on depends_on_temp_id)."""

    task_temp_id: uuid.UUID
    depends_on_temp_id: uuid.UUID


@dataclass
class MissionPlan:
    """Complete validated plan generated by a MissionPlanner."""

    tasks: list[PlannedTask]
    dependencies: list[PlannedDependency]
    plan_version: str = "1.0.0"
    metadata: dict[str, Any] = field(default_factory=dict)


class MissionPlanner(ABC):
    """Abstract base class for mission planners."""

    @abstractmethod
    def plan(self, mission_title: str, mission_objective: str, autonomy_level: str) -> MissionPlan:
        """Generate and validate a task DAG for the given mission parameters."""
        pass


class StaticMissionPlanner(MissionPlanner):
    """Static deterministic workflow planner generating a standard 7-stage content DAG.

    Stages:
    1. Strategy (root)
    2. Topic Discovery (depends on Strategy)
    3. Research (depends on Topic Discovery)
    4. Content Generation (depends on Research)
    5. Production (depends on Content Generation)
    6. QA (depends on Production; requires approval in SUPERVISED / ASSISTED)
    7. Publish (depends on QA)
    """

    def plan(self, mission_title: str, mission_objective: str, autonomy_level: str) -> MissionPlan:
        strategy_id = uuid.uuid4()
        topic_id = uuid.uuid4()
        research_id = uuid.uuid4()
        content_id = uuid.uuid4()
        prod_id = uuid.uuid4()
        qa_id = uuid.uuid4()
        publish_id = uuid.uuid4()

        # In SUPERVISED/ASSISTED, the QA stage requires human approval before publish
        requires_qa_approval = autonomy_level in ("SUPERVISED", "ASSISTED", "MANUAL")

        tasks = [
            PlannedTask(
                temp_id=strategy_id,
                task_create=TaskCreate(
                    task_type="strategy",
                    title="Content Strategy & Direction",
                    description=f"Formulate strategic angle for: {mission_objective[:100]}",
                    priority=1,
                    requires_approval=False,
                    input={"objective": mission_objective},
                ),
            ),
            PlannedTask(
                temp_id=topic_id,
                task_create=TaskCreate(
                    task_type="topic_discovery",
                    title="Topic Discovery & Keyword Mapping",
                    description="Identify core subject themes and engagement vectors.",
                    priority=2,
                    requires_approval=False,
                    input={},
                ),
            ),
            PlannedTask(
                temp_id=research_id,
                task_create=TaskCreate(
                    task_type="research",
                    title="Deep Research & Fact Verification",
                    description="Compile verified source material and key arguments.",
                    priority=3,
                    requires_approval=False,
                    input={},
                ),
            ),
            PlannedTask(
                temp_id=content_id,
                task_create=TaskCreate(
                    task_type="content_generation",
                    title="Draft Content Generation",
                    description="Structure narrative flow and create foundational copy.",
                    priority=4,
                    requires_approval=False,
                    input={},
                ),
            ),
            PlannedTask(
                temp_id=prod_id,
                task_create=TaskCreate(
                    task_type="production",
                    title="Media Asset Assembly",
                    description="Assemble visual cues, sound design, and metadata package.",
                    priority=5,
                    requires_approval=False,
                    input={},
                ),
            ),
            PlannedTask(
                temp_id=qa_id,
                task_create=TaskCreate(
                    task_type="qa",
                    title="Quality Review & Editorial Sign-off",
                    description="Validate brand alignment, factual rigor, and tone.",
                    priority=6,
                    requires_approval=requires_qa_approval,
                    input={},
                ),
            ),
            PlannedTask(
                temp_id=publish_id,
                task_create=TaskCreate(
                    task_type="publish",
                    title="Distribution & Channel Dispatch",
                    description="Package for target publication channels.",
                    priority=7,
                    requires_approval=False,
                    input={},
                ),
            ),
        ]

        dependencies = [
            PlannedDependency(task_temp_id=topic_id, depends_on_temp_id=strategy_id),
            PlannedDependency(task_temp_id=research_id, depends_on_temp_id=topic_id),
            PlannedDependency(task_temp_id=content_id, depends_on_temp_id=research_id),
            PlannedDependency(task_temp_id=prod_id, depends_on_temp_id=content_id),
            PlannedDependency(task_temp_id=qa_id, depends_on_temp_id=prod_id),
            PlannedDependency(task_temp_id=publish_id, depends_on_temp_id=qa_id),
        ]

        # Validate DAG acyclicity
        task_id_set = {t.temp_id for t in tasks}
        dep_tuples = [(d.task_temp_id, d.depends_on_temp_id) for d in dependencies]
        validate_dag(task_id_set, dep_tuples)

        return MissionPlan(
            tasks=tasks,
            dependencies=dependencies,
            plan_version="1.0.0",
            metadata={
                "planner": "StaticMissionPlanner",
                "stages_count": len(tasks),
                "title": mission_title,
            },
        )
