"""Subtitle generation, SRT formatting, and file export."""

from __future__ import annotations

import uuid
from typing import Any

from omega.application.media_storage import LocalMediaStorageProvider, compute_sha256
from omega.domain.production import (
    AssetProviderType,
    AssetType,
    LicenseStatus,
)


def format_srt_time(ms: int) -> str:
    """Format milliseconds into SRT timestamp format: HH:MM:SS,mmm."""
    ms = max(ms, 0)
    hours = ms // 3600000
    ms %= 3600000
    minutes = ms // 60000
    ms %= 60000
    seconds = ms // 1000
    millis = ms % 1000
    return f"{hours:02d}:{minutes:02d}:{seconds:02d},{millis:03d}"


def generate_srt_content(subtitle_cues: list[dict[str, Any]]) -> str:
    """Serialize subtitle cues into canonical SubRip (.srt) string."""
    blocks: list[str] = []
    for cue in sorted(subtitle_cues, key=lambda c: int(c.get("cue_order", 0))):
        order = cue.get("cue_order", 1)
        start_time = format_srt_time(int(cue.get("start_ms", 0)))
        end_time = format_srt_time(int(cue.get("end_ms", 0)))
        text = str(cue.get("text", "")).strip()

        block = f"{order}\n{start_time} --> {end_time}\n{text}\n"
        blocks.append(block)

    return "\n".join(blocks)


class SubtitleEngine:
    """Engine for writing subtitle files to media storage."""

    def __init__(self, storage: LocalMediaStorageProvider) -> None:
        self.storage = storage

    def export_srt_file(
        self,
        channel_id: uuid.UUID,
        request_id: uuid.UUID,
        subtitle_cues: list[dict[str, Any]],
    ) -> dict[str, Any]:
        """Generate and save `.srt` file and return asset metadata."""
        subtitles_dir = self.storage.get_subtitles_dir(channel_id, request_id)
        asset_id = uuid.uuid4()
        target_path = subtitles_dir / f"subtitles_{asset_id.hex[:10]}.srt"

        srt_text = generate_srt_content(subtitle_cues)
        target_path.write_text(srt_text, encoding="utf-8")

        content_hash = compute_sha256(target_path)
        rel_uri = self.storage.to_relative_uri(channel_id, request_id, target_path)

        return {
            "id": asset_id,
            "channel_id": channel_id,
            "production_request_id": request_id,
            "asset_requirement_id": None,
            "asset_type": AssetType.SUBTITLE.value
            if hasattr(AssetType, "SUBTITLE")
            else "SUBTITLE",
            "provider_type": AssetProviderType.SYSTEM.value,
            "storage_uri": rel_uri,
            "content_hash": content_hash,
            "mime_type": "application/x-subrip",
            "width": None,
            "height": None,
            "duration_ms": None,
            "license_status": LicenseStatus.OWNED.value,
            "source_ref": "Generated Subtitles",
            "attribution": "Generated by OMEGA Subtitle Engine",
        }
